site_name: Markdown Manuals for Bioinformatics Training Platform (BTP)
site_description: This contains all material for Markdown version of BTP workshops.
site_author: Authors

#site_url: 'https://bpa-csiro-workshops.github.io/metagenomics-manuals'

copyright: '&copy; The authors; 2017-'

#Documentation and theme
theme: material

# Options
extra:
  palette:
    primary: 'indigo'
    accent: 'light blue'

  feature:
    tabs: true

  site_favicon: 'media/logos/Bioplatforms-Australia-favicon2.png'

markdown_extensions:
    - admonition
    - smarty
    - tables
    - markdown_include.include
    - codehilite(linenums=True)
#    - codehilite
    - toc(permalink=true)
    - mdx_math
    - pymdownx.betterem(smart_enable=all)
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist(custom_checkbox=true)
    - pymdownx.tilde
    - pymdownx.details

extra_css:
    #- css/extra.css
    - css/details.css

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML
    - js/details.js

pages:
- Home: index.md
- The Trainers: trainers/trainers.md
- Timetable:
  #- Intro to NGS: timetables/timetable_introNGS.md
  #- Cancer Genomics: timetables/timetable_cancer.md
  #- Long Read: timetables/timetable_longRead.md
  - Metagenomics: timetables/timetable_longRead.md
- Workshop Information: preamble.md

# - All Modules:
#     - ChIP-seq: modules/btp-module-chip-seq/chip-seq.md
#     - DeNovo Canu: modules/btp-module-denovo-canu/denovo_canu.md
#     - NGS Biological Insight: modules/btp-module-ngs-bio/biol.md
#     - NGS Introduction to Command Line: modules/btp-module-ngs-cli/commandline.md
#     - NGS Read Alignment: modules/btp-module-ngs-mapping/alignment.md
#     - NGS Data Quality: modules/btp-module-ngs-qc/ngs-qc.md
#     - RNA-Seq: modules/btp-module-rna-seq/rna-seq.md
#     - de novo Genome Assembly with Velvet: modules/btp-module-velvet/velvet.md
#     - Cancer Read Alignment: modules/cancer-module-alignment/alignment.md
#     - Copy Number Variation: modules/cancer-module-cnv/cnv-tut.md
#     - Single Nucleotide Variant Calling and Annotation: modules/cancer-module-snv/snv.md
#     - Somatic Mutations:
#         - Assessing somatic mutational signatures: modules/cancer-module-somatic/01_signatures.md
#         - Cohort analysis for the identification of driver genes: modules/cancer-module-somatic/02_intogen.md
#     - Structural Variant Analysis: modules/cancer-module-sv/sv_tut.md
#     - Cancer Variant Visualisation: modules/cancer-module-viz/visu.md
#     - Bacterial Assembly: modules/denovo-module-bac/bac_asm.md
#     - DeNovo Introduction to Command Line: modules/denovo-module-cli/commandline.md
#     - Eukaryote Assembly: modules/denovo-module-euk/eukaryotic_assem.md
#     - Scaffolding: modules/denovo-module-scaffolding/scaffold.md
#     - Metagenomics Functional Analysis:
#         - Functional Analysis using EMG: modules/metagenomics-module-fda/fda.md
#     - Metagenomics mining EMG with R:
#         - Mining EMG with R part 1: modules/metagenomics-module-emgr/emgr-part1.md
#         - Mining EMG with R part 2A: modules/metagenomics-module-emgr/emgr-part2A.md
#         - Mining EMG with R part 2B: modules/metagenomics-module-emgr/emgr-part2B.md
#     - Metagenomics Data Quality: modules/metagenomics-module-qc/ngs-qc.md
#     - Metagenomics Taxonomic : modules/metagenomics-module-tax/tax.md
#     - Metagenomics Visualisation: modules/metagenomics-module-vis/vis.md
#     - Metagenomics WGA: modules/metagenomics-module-wga/wga.md

#- Introduction to NGS Modules:
#    - Introduction to Command Line: modules/btp-module-ngs-cli/commandline.md
#    - Data Quality: modules/btp-module-ngs-qc/ngs-qc.md
#    - Read Alignment: modules/btp-module-ngs-mapping/alignment.md
#    - ChIP-seq: modules/btp-module-chip-seq/chip-seq.md
#    - RNA-Seq: modules/btp-module-rna-seq/rna-seq.md
#    - NGS Biological Insight: modules/btp-module-ngs-bio/biol.md
#    - de novo Genome Assembly: modules/btp-module-velvet/velvet.md
#    - DeNovo Canu: modules/btp-module-denovo-canu/denovo_canu.md

#- Cancer Genomics Modules:
#    - Read Alignment: modules/cancer-module-alignment/alignment.md
#    - Single Nucleotide Variant Calling and Annotation: modules/cancer-module-snv/snv.md
#    - Copy Number Variation: modules/cancer-module-cnv/cnv-tut.md
#    - Structural Variant Analysis: modules/cancer-module-sv/sv_tut.md
#    - Variant Visualisation: modules/cancer-module-viz/visu.md
#    - Somatic Mutations:
#        - Assessing somatic mutational signatures: modules/cancer-module-somatic/01_signatures.md
#        - Cohort analysis for the identification of driver genes: modules/cancer-module-somatic/02_intogen.md

#- DeNovo Modules:
#    - DeNovo Command Line: modules/denovo-module-cli/commandline.md
#    - Bacterial Assembly: modules/denovo-module-bac/bac_asm.md
#    - Eukaryote Assembly: modules/denovo-module-euk/eukaryotic_assem.md
#    - Scaffolding: modules/denovo-module-scaffolding/scaffold.md

- Metagenomics Modules:
    - Metagenomics QC: modules/metagenomics-module-qc/ngs-qc.md
    - Metagenomics Taxonomic: modules/metagenomics-module-tax/tax.md
    - Metagenomics Visualisation: modules/metagenomics-module-vis/vis.md
    - Metagenomics WGA: modules/metagenomics-module-wga/wga.md
    - Metagenomics Functional Analysis: modules/metagenomics-module-fda/fda.md
